# Generated by Django 5.1.6 on 2025-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('image_url', models.ImageField(upload_to='gambar/')),
                ('category', models.CharField(choices=[('assaultrifle', 'Assault Rifle'), ('sniper', 'Sniper Rifle'), ('machinegun', 'Machine Gun'), ('grenadelauncher', 'Grenade Launcher'), ('mortir', 'Mortir'), ('pistol', 'Pistol'), ('shotgun', 'Shotgun'), ('submachinegun', 'Submachine Gun'), ('homemadeexplosive', 'Hommade Explosive Part')], max_length=255)),
                ('stock', models.IntegerField()),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
